// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDseoJ9_qfi051P4pWGoMbryyiV7OrPTJc',
    appId: '1:410348576673:web:db31e2e7702d22b2c575e0',
    messagingSenderId: '410348576673',
    projectId: 'findit-6921b',
    authDomain: 'findit-6921b.firebaseapp.com',
    storageBucket: 'findit-6921b.firebasestorage.app',
    measurementId: 'G-DH9VE7B0CF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYvhGQ-oTecA1kIPKm2jfCMNoLrUZ-JiU',
    appId: '1:410348576673:android:54c5058a3ff6fe36c575e0',
    messagingSenderId: '410348576673',
    projectId: 'findit-6921b',
    storageBucket: 'findit-6921b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk5dj4kvbewg-bRnTaaGQAOR9k0zZlpCc',
    appId: '1:410348576673:ios:6f925d27d3219798c575e0',
    messagingSenderId: '410348576673',
    projectId: 'findit-6921b',
    storageBucket: 'findit-6921b.firebasestorage.app',
    androidClientId: '410348576673-4v3h84e9inv6s5nke7kn3i4ukfac7ln2.apps.googleusercontent.com',
    iosClientId: '410348576673-bcl8k0fb50c2o1oqd87ooh4ic462n4f5.apps.googleusercontent.com',
    iosBundleId: 'com.example.findZero',
  );
}
